### ISSUE TITLE
Does not exist in the repository

### ISSUE THREAD

**Issue by kkange** [grumpyshoe/android-module-pushmanager#2]
Hi good lib

But

Does not exist in the repository

**Comment by grumpyshoe** [comment]
Maybe you missed to add the jitpack repository?

```
allprojects {
    repositories {
        ...
        maven { url "https://jitpack.io" }
    }
    ...
}
```


I added a section to the README, thanks for your feedback 👍

**Comment by kkange** [comment]
ok thanks
